<a href="https://colab.research.google.com/github/zuhri05-code/telegram_bot/blob/main/Corpus3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install numpy==1.26.4 scipy==1.11.4 gensim==4.3.2 --force-reinstall --quiet


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 49.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.8/35.8 MB 12.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 kB 8.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.1 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.11.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<

In [2]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [3]:
# =====================================
# Feature Extraction NLP (Google Colab)
# =====================================

# Install pustaka (Colab biasanya fresh)
!pip install scikit-learn gensim nltk --quiet

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec
import nltk

# Download resource NLTK (punkt = tokenizer, stopwords optional)
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)

# -------------------------------------
# Dataset sederhana (corpus)
# -------------------------------------
corpus = [
    "Natural Language Processing is a subfield of Artificial Intelligence",
    "Neural Networks are widely used in NLP tasks",
    "Feature extraction is important in text analysis"
]

# -------------------------------------
# 1. Bag of Words (BoW)
# -------------------------------------
vectorizer_bow = CountVectorizer()
X_bow = vectorizer_bow.fit_transform(corpus)

print("=== Bag of Words ===")
print(vectorizer_bow.get_feature_names_out())
print(X_bow.toarray())

# -------------------------------------
# 2. TF-IDF
# -------------------------------------
vectorizer_tfidf = TfidfVectorizer()
X_tfidf = vectorizer_tfidf.fit_transform(corpus)

print("\n=== TF-IDF ===")
print(vectorizer_tfidf.get_feature_names_out())
print(X_tfidf.toarray())

# -------------------------------------
# 3. Word Embeddings (Word2Vec)
# -------------------------------------
# Tokenisasi
tokenized_corpus = [nltk.word_tokenize(doc.lower()) for doc in corpus]

# Latih Word2Vec
model_w2v = Word2Vec(
    sentences=tokenized_corpus,
    vector_size=50,
    window=3,
    min_count=1,
    workers=4
)

print("\n=== Word2Vec Embedding (contoh kata 'nlp') ===")
print(model_w2v.wv['nlp'])  # vektor representasi untuk kata 'nlp'


=== Bag of Words ===
['analysis' 'are' 'artificial' 'extraction' 'feature' 'important' 'in'
 'intelligence' 'is' 'language' 'natural' 'networks' 'neural' 'nlp' 'of'
 'processing' 'subfield' 'tasks' 'text' 'used' 'widely']
[[0 0 1 0 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 1 1]
 [1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0]]

=== TF-IDF ===
['analysis' 'are' 'artificial' 'extraction' 'feature' 'important' 'in'
 'intelligence' 'is' 'language' 'natural' 'networks' 'neural' 'nlp' 'of'
 'processing' 'subfield' 'tasks' 'text' 'used' 'widely']
[[0.         0.         0.36325471 0.         0.         0.
  0.         0.36325471 0.27626457 0.36325471 0.36325471 0.
  0.         0.         0.36325471 0.36325471 0.36325471 0.
  0.         0.         0.        ]
 [0.         0.36325471 0.         0.         0.         0.
  0.27626457 0.         0.         0.         0.         0.36325471
  0.36325471 0.36325471 0.         0.         0.         0.36325471
  0.         